name: Codacy Security Scan

on:
  push:
    branches: [ "master", "main" , "auth"]
  pull_request:
    branches: [ "master", "main" , "auth"]

  workflow_dispatch:
<<<<<<< HEAD
        inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
=======

>>>>>>> b80bb47938ef916c71b994b36f9b80560e01f24b
jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.sarif
          format: sarif
          # Adjust severity of non-security issues
          gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will handover control about PR rejection to the GitHub side
          max-allowed-issues: 2147483647
      
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif
<<<<<<< HEAD

=======
>>>>>>> b80bb47938ef916c71b994b36f9b80560e01f24b
